# Conclusion and Recommendations
## Findings
The boxplot in Figure 1 (Section 2.2) created questions around two main takeaways from our project: the mean ratings across locations and features to a linear explanatory model. We addressed:

 - The mean ratings across NYC and Raleigh.

 - Variable importance from the linear regression model and random forest model, where the linear regression model utilized stepwise selection to select significant explanatory variables with AIC metrics, and the random forest model confirmed that the cities feature was important in mean boba shop rating outcomes.

In Raleigh, Asian fusion and bakeries were important factors to secure high ratings. Conversely, in NYC, authenticity and the offering of custom cakes played key roles. These findings suggest that customers in NYC seem to have higher expectations as compared with customers in Raleigh, which was further supported after visual comparisons of each location data set.

We attribute the high overlap of the explanatory and predictive variables in part to physical shop proximity, as seen on the Tableau dashboard. This file is available in the Xiaolongbao repository, and you can find it in the file named "boba_tab.twbx" if additional loading is required.

## Next Steps
From our conclusion, we recommend that aspiring businesses considering a new boba shop could:

 - Understand the preferences and expectations of potential customers.
 
 - Prepare to face the competition in the area.

Our findings emphasize that what garners a high rating in one location may not necessarily translate to the same acclaim in another location, especially in densely populated cities.

Looking ahead, this project encourages future comparative studies of bubble tea shops in different areas across the country or even the world. Expanding the analysis to include major metropolitan locations like Los Angeles or Chicago could uncover broader trends in boba shop dynamics, providing entrepreneurs with valuable insights for navigating diverse urban landscapes. 