--- 
title: "An Analysis of Boba Yelp Reviews"
author: "Violet Evans and Gloria Su"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction
Here, we present a background of our 2023 statistical side project: An Analysis of Boba Yelp Reviews. This project is co-authored by two M.S. in Analytics students at North Carolina State University, Violet Evans and Gloria Su. The inspiration behind our side project came from our love for bubble tea, a staple of Asian American culture. 

Bubble tea, also known as boba, is a sweet Taiwanese drink that has grown in popularity across the world since 1988 (Wei, 2023). Much of this growing popularity started from a new generation of young Asian Americans, who spread the drink to friends and neighbors from all different cultural backgrounds (Zhang, 2019). As Asian Americans raised in North Carolina, we frequently longed for authentic Asian cuisines in the Triangle that would reconnect us with our heritage. Growing up, boba culture wasn't large. However, the popularity of boba in the broader Raleigh-Durham-Chapel Hill area (the Triangle) has surged, coinciding with the arrival of nearly 40,000 households and businesses between 2018 and 2022. This growth has brought a number of trendy Asian boba shops to the Triangle region. Not only has the number of shops increased, but there also has been a rise in the count of Yelp reviews for each individual shop.

Due to the extensive variety of boba shop offerings, spanning from milk tea to fruit tea, there has never been widely recognized standards for defining a good drink. Our project goal is to examine the criteria for a successful boba shop by utilizing the Fusion API to analyze ratings and reviews from the Yelp business directory.

The inspiration behind our Yelp API project came from a day in the library after studying for our statistical foundations class. We were chatting about our favorite boba drinks, and the conversation led to our own debate over what truly was the best boba shop in the area. One idea led to another and we began delving into what a statistical side project could look like on a topic we were invested in— and thus began “An Analysis of Boba Yelp Reviews.”

